apiVersion: v1
kind: Pod
metadata:
  name: test-json-log
  namespace: ml-scraper
spec:
  containers:
  - name: scraper
    image: ml-scraper:v9
    command: ["sleep", "300"]
    env:
    - name: LOG_DIR
      value: "/dev/null"
  restartPolicy: Never
