apiVersion: v1
kind: ConfigMap
metadata:
  name: scraper-config
data:
  BROWSER: "chrome"
  HEADLESS: "true"
  LOG_LEVEL: "INFO"
  RESULT_LIMIT: "30"
  POSTGRES_ENABLED: "true"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "scraper"
  POSTGRES_PASSWORD: "scraper123"
  POSTGRES_DB: "scraperdb"
  PRODUCTS: |
    bicicleta rodado 29
    iPhone 16 Pro Max
    GeForce RTX 5090
