apiVersion: v1
kind: ConfigMap
metadata:
  name: scraper-config
  namespace: sip-selenium
data:
  BROWSER: "chrome"
  HEADLESS: "true"
  LOG_LEVEL: "INFO"
  RESULT_LIMIT: "30"
  POSTGRES_ENABLED: "true"
  PRODUCTS: |
    bicicleta rodado 29
    iPhone 16 Pro Max
    GeForce RTX 5090
