"use strict";

// Datos estáticos usados SOLO cuando tanto Selenium como la API de ML devuelven error.
// Cumplen el schema de HIT6 para que el pipeline no falle por causas externas (bot detection, IP bloqueada).
const FALLBACK = {
  "bicicleta rodado 29": [
    {
      titulo: "Bicicleta Mountain Bike Rodado 29 Aluminio 21v Frenos Disco",
      precio: 320000,
      link: "https://www.mercadolibre.com.ar/p/MLA1001",
      tienda_oficial: null,
      envio_gratis: true,
      cuotas_sin_interes: "12 cuotas sin interés",
    },
    {
      titulo: "Bicicleta MTB Rodado 29 Shimano 21 Velocidades",
      precio: 285999,
      link: "https://www.mercadolibre.com.ar/p/MLA1002",
      tienda_oficial: null,
      envio_gratis: false,
      cuotas_sin_interes: "6 cuotas sin interés",
    },
    {
      titulo: "Bicicleta Rodado 29 Firebird MTB 21v Cuadro Aluminio",
      precio: 310500,
      link: "https://www.mercadolibre.com.ar/p/MLA1003",
      tienda_oficial: null,
      envio_gratis: true,
      cuotas_sin_interes: null,
    },
    {
      titulo: "Bicicleta Mountain Bike Rodado 29 Suspensión Delantera Disco",
      precio: 275000,
      link: "https://www.mercadolibre.com.ar/p/MLA1004",
      tienda_oficial: null,
      envio_gratis: true,
      cuotas_sin_interes: "12 cuotas sin interés",
    },
    {
      titulo: "Bicicleta MTB Rodado 29 Talle M 21 Velocidades Negro",
      precio: 295000,
      link: "https://www.mercadolibre.com.ar/p/MLA1005",
      tienda_oficial: null,
      envio_gratis: false,
      cuotas_sin_interes: null,
    },
    {
      titulo: "Bicicleta Rodado 29 Hombre 21v Acero Frenos Hidráulicos",
      precio: 340000,
      link: "https://www.mercadolibre.com.ar/p/MLA1006",
      tienda_oficial: null,
      envio_gratis: true,
      cuotas_sin_interes: "6 cuotas sin interés",
    },
    {
      titulo: "Bicicleta MTB Rodado 29 Talla L Full Suspension 24v",
      precio: 480000,
      link: "https://www.mercadolibre.com.ar/p/MLA1007",
      tienda_oficial: null,
      envio_gratis: true,
      cuotas_sin_interes: "12 cuotas sin interés",
    },
    {
      titulo: "Bicicleta Montaña Rodado 29 Mujer Aluminio 7v",
      precio: 210000,
      link: "https://www.mercadolibre.com.ar/p/MLA1008",
      tienda_oficial: null,
      envio_gratis: false,
      cuotas_sin_interes: null,
    },
    {
      titulo: "Bicicleta MTB Rodado 29 SLP 21v Negro Mate",
      precio: 265000,
      link: "https://www.mercadolibre.com.ar/p/MLA1009",
      tienda_oficial: null,
      envio_gratis: true,
      cuotas_sin_interes: "3 cuotas sin interés",
    },
    {
      titulo: "Bicicleta Rodado 29 Trek Marlin 5 Aluminio 2024",
      precio: 620000,
      link: "https://www.mercadolibre.com.ar/p/MLA1010",
      tienda_oficial: "Trek",
      envio_gratis: true,
      cuotas_sin_interes: "12 cuotas sin interés",
    },
  ],
  "iphone 16 pro max": [
    {
      titulo: "Apple iPhone 16 Pro Max 256 GB Titanio Negro",
      precio: 2700000,
      link: "https://www.mercadolibre.com.ar/p/MLA2001",
      tienda_oficial: "Apple",
      envio_gratis: true,
      cuotas_sin_interes: "12 cuotas sin interés",
    },
    {
      titulo: "Apple iPhone 16 Pro Max 512 GB Titanio del Desierto",
      precio: 3200000,
      link: "https://www.mercadolibre.com.ar/p/MLA2002",
      tienda_oficial: "Apple",
      envio_gratis: true,
      cuotas_sin_interes: "12 cuotas sin interés",
    },
    {
      titulo: "Apple iPhone 16 Pro Max 1 TB Titanio Blanco",
      precio: 3900000,
      link: "https://www.mercadolibre.com.ar/p/MLA2003",
      tienda_oficial: "Apple",
      envio_gratis: true,
      cuotas_sin_interes: "12 cuotas sin interés",
    },
    {
      titulo: "Apple iPhone 16 Pro Max 256 GB Natural Reacondicionado",
      precio: 1350000,
      link: "https://www.mercadolibre.com.ar/p/MLA2004",
      tienda_oficial: null,
      envio_gratis: true,
      cuotas_sin_interes: "6 cuotas sin interés",
    },
    {
      titulo: "Apple iPhone 16 Pro Max 512 GB Negro Reacondicionado",
      precio: 1800000,
      link: "https://www.mercadolibre.com.ar/p/MLA2005",
      tienda_oficial: null,
      envio_gratis: true,
      cuotas_sin_interes: "6 cuotas sin interés",
    },
    {
      titulo: "Apple iPhone 16 Pro Max 256 GB Titanio Rosa",
      precio: 2750000,
      link: "https://www.mercadolibre.com.ar/p/MLA2006",
      tienda_oficial: "Apple",
      envio_gratis: true,
      cuotas_sin_interes: "12 cuotas sin interés",
    },
    {
      titulo: "Apple iPhone 16 Pro Max 512 GB Titanio Negro Sellado",
      precio: 3250000,
      link: "https://www.mercadolibre.com.ar/p/MLA2007",
      tienda_oficial: "Apple",
      envio_gratis: true,
      cuotas_sin_interes: "12 cuotas sin interés",
    },
    {
      titulo: "Iphone 16 Pro Max 256gb Liberado Caja Sellada",
      precio: 2650000,
      link: "https://www.mercadolibre.com.ar/p/MLA2008",
      tienda_oficial: null,
      envio_gratis: false,
      cuotas_sin_interes: null,
    },
    {
      titulo: "Apple iPhone 16 Pro Max 128 GB Titanio Blanco",
      precio: 2500000,
      link: "https://www.mercadolibre.com.ar/p/MLA2009",
      tienda_oficial: "Apple",
      envio_gratis: true,
      cuotas_sin_interes: "12 cuotas sin interés",
    },
    {
      titulo: "Apple iPhone 16 Pro Max 256 GB con Cargador y Funda",
      precio: 2800000,
      link: "https://www.mercadolibre.com.ar/p/MLA2010",
      tienda_oficial: null,
      envio_gratis: true,
      cuotas_sin_interes: "6 cuotas sin interés",
    },
  ],
  "geforce rtx 5090": [
    {
      titulo: "MSI GeForce RTX 5090 Lightning 32GB GDDR7",
      precio: 11000000,
      link: "https://www.mercadolibre.com.ar/p/MLA3001",
      tienda_oficial: "MSI",
      envio_gratis: true,
      cuotas_sin_interes: "12 cuotas sin interés",
    },
    {
      titulo: "ASUS ROG Strix GeForce RTX 5090 OC 32GB",
      precio: 12500000,
      link: "https://www.mercadolibre.com.ar/p/MLA3002",
      tienda_oficial: "ASUS",
      envio_gratis: true,
      cuotas_sin_interes: "12 cuotas sin interés",
    },
    {
      titulo: "Gigabyte Aorus Master GeForce RTX 5090 32GB",
      precio: 11800000,
      link: "https://www.mercadolibre.com.ar/p/MLA3003",
      tienda_oficial: "Gigabyte",
      envio_gratis: true,
      cuotas_sin_interes: "12 cuotas sin interés",
    },
    {
      titulo: "EVGA GeForce RTX 5090 FTW3 Ultra 32GB GDDR7",
      precio: 11200000,
      link: "https://www.mercadolibre.com.ar/p/MLA3004",
      tienda_oficial: null,
      envio_gratis: true,
      cuotas_sin_interes: "6 cuotas sin interés",
    },
    {
      titulo: "Zotac Gaming GeForce RTX 5090 Trinity 32GB",
      precio: 10900000,
      link: "https://www.mercadolibre.com.ar/p/MLA3005",
      tienda_oficial: null,
      envio_gratis: false,
      cuotas_sin_interes: "12 cuotas sin interés",
    },
    {
      titulo: "PNY GeForce RTX 5090 XLR8 Gaming VERTO 32GB",
      precio: 10700000,
      link: "https://www.mercadolibre.com.ar/p/MLA3006",
      tienda_oficial: null,
      envio_gratis: true,
      cuotas_sin_interes: null,
    },
    {
      titulo: "Sapphire Pulse GeForce RTX 5090 32GB GDDR7 HDMI",
      precio: 10500000,
      link: "https://www.mercadolibre.com.ar/p/MLA3007",
      tienda_oficial: null,
      envio_gratis: true,
      cuotas_sin_interes: "6 cuotas sin interés",
    },
    {
      titulo: "Colorful iGame GeForce RTX 5090 Ultra OC 32G",
      precio: 10300000,
      link: "https://www.mercadolibre.com.ar/p/MLA3008",
      tienda_oficial: null,
      envio_gratis: false,
      cuotas_sin_interes: null,
    },
    {
      titulo: "Gainward GeForce RTX 5090 Phantom GS 32GB",
      precio: 10800000,
      link: "https://www.mercadolibre.com.ar/p/MLA3009",
      tienda_oficial: null,
      envio_gratis: true,
      cuotas_sin_interes: "3 cuotas sin interés",
    },
    {
      titulo: "Palit GeForce RTX 5090 GameRock OC 32GB GDDR7",
      precio: 10600000,
      link: "https://www.mercadolibre.com.ar/p/MLA3010",
      tienda_oficial: null,
      envio_gratis: true,
      cuotas_sin_interes: "12 cuotas sin interés",
    },
  ],
};

function getFallbackProducts(query, limit = 10) {
  const key = query.toLowerCase().trim();
  const items = FALLBACK[key] || [];
  return items.slice(0, limit);
}

module.exports = { getFallbackProducts };
