apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper-hourly
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: scraper
              securityContext:
                runAsUser: 0
              image: ml-scraper:v8
              imagePullPolicy: IfNotPresent
              command: ["node", "HIT5/src/scrapers/mercadolibre.js"]
              envFrom:
                - configMapRef:
                    name: scraper-config
              volumeMounts:
                - name: output
                  mountPath: /app/output
          volumes:
            - name: output
              persistentVolumeClaim:
                claimName: scraper-output
