apiVersion: v1
kind: Service
metadata:
  name: kibana-nodeport
  namespace: elastic
spec:
  type: NodePort
  selector:
    kibana.k8s.elastic.co/name: quickstart
  ports:
    - name: http
      port: 5601
      targetPort: 5601
      nodePort: 30001
